catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
minimumReleaseAgeExclude:
  - "@react-aria/optimize-locales-plugin@2.0.0"
  - "@react-types/shared@3.36.0"
  - react-aria-components@1.19.0
  - react-aria@3.50.0
  - react-stately@3.48.0
  - tailwindcss-react-aria-components@2.2.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
